begin;

create table pbp.matchups (
       game_id					text,
       start_time				interval,
       end_time					interval,
       elapsed_time				interval,
       elapsed_secs				integer,
       home_player1_id				integer,
       home_player2_id				integer,
       home_player3_id				integer,
       home_player4_id				integer,
       home_player5_id				integer,
       away_player1_id				integer,
       away_player2_id				integer,
       away_player3_id				integer,
       away_player4_id				integer,
       away_player5_id				integer,
       home_player1_name			text,
       home_player2_name			text,
       home_player3_name			text,
       home_player4_name			text,
       home_player5_name			text,
       away_player1_name			text,
       away_player2_name			text,
       away_player3_name			text,
       away_player4_name			text,
       away_player5_name			text,
       start_score_home				text,
       start_score_away				integer,
       end_score_home				integer,
       end_score_away				integer,
       points_scored_home			integer,
       points_scored_away			integer,
       plus_minus_home				float,
       plus_minus_away				float,
       possessions_home				integer,
       possessions_away				integer,
       offensive_rtg_home			float,
       offensive_rtg_away			float,
       overall_rtg_home_vs_away			float,
       overall_rtg_away_vs_home			float,
       offensive_rebounds_home			integer,
       offensive_rebounds_away			integer,
       defensive_rebounds_home			integer,
       defensive_rebounds_away			integer,
       offensive_rebounding_rate_home		float,
       offensive_rebounding_rate_away		float,
       defensive_rebounding_rate_home		float,
       defensive_rebounding_rate_away		float
);

copy pbp.matchups from '/tmp/matchups.csv' with delimiter as E'\t' csv header quote as '"';

commit;
